[project]
name = "buchelib"
version = "0.0.6"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Olivier Breuleux", email = "breuleux@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "hypetext>=0.0.4",
    "ovld>=0.5.17",
    "serieux>=0.3.13",
]

[build-system]
requires = ["uv_build>=0.9.3,<0.10.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 99

[tool.ruff.lint]
extend-select = ["I"]
ignore = ["F811", "F722"]

[tool.ruff.lint.isort]
combine-as-imports = true
